# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloudConnection'
    organization: 'softwaretoolsgroupproject'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'SoftwareToolsGroupProject_RentalSystem'
    cliProjectName: 'DVD Rental SYS'
    cliSources: '.'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
- task: Npm@1
  displayName: jest tests
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'run test:ci'


    

