# Starter pipeline
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloudConnection'
    organization: 'softwaretoolsgroupproject'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'SoftwareToolsGroupProject_RentalSystem'
    cliProjectName: 'DVD Rental SYS'
    cliSources: '.'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
