CREATE TABLE DVDs (
DVDID INT(10)  UNSIGNED,
	Title VARCHAR2(30) NOT NULL  ,
	Director VARCHAR2(30) NOT NULL  ,
	Factory VARCHAR2(25) NOT NULL  ,
	Year NVARCHAR2(4) NOT NULL  ,
	Edition VARCHAR2(25) NOT NULL  ,
	Genre CHAR(2) NOT NULL  ,
Cost DECIMAL(5,2), 
	Status CHAR(1) NOT NULL,
	CONSTRAINT pk_DVDID PRIMARY KEY (DVDID)
);

CREATE TABLE Members (
	MemberID INT(10) UNSIGNED,
	Forename VARCHAR2(20) NOT NULL  ,
	Surname VARCHAR(30) NOT NULL  ,
	Password VARCHAR (256) NOT NULL
	Street VARCHAR2(50) NOT NULL  ,
	Town VARCHAR2(20) NOT NULL  ,
	County CHAR(2) NOT NULL  ,
	Eircode CHAR(7) NOT NULL  ,
	Phone CHAR(10) NOT NULL  ,
	Email VARCHAR2(100)   ,
	DOB Date NOT NULL  ,
	Status CHAR(1) ,
	CONSTRAINT PK_MemberID PRIMARY KEY (MemberID)
);

CREATE TABLE Rentals (
RentalID INT(10) UNSIGNED ,
	MemberID NUMERIC(6) NOT NULL  ,
DVDID NUMERIC(6) ,
RentalDate Date NOT NULL ,
RentalDueDate DATE,
	Status CHAR(1) NOT NULL,
	CONSTRAINT PK_RentalID PRIMARY KEY (RentalID),
	CONSTRAINT FK_MemberID FOREIGN KEY (MemberID) REFERENCES Members(MemberID),
	CONSTRAINT FK_DVDID FOREIGN KEY (DVDID) REFERENCES DVDs(DVDID)
 );

