

CREATE TABLE DVDs (
DVDID INT(6) UNSIGNED,
	Title VARCHAR(30) NOT NULL  ,
	Genre VARCHAR(1),
	Duration TIME,
	Rating DECIMAL(4,2),
Cost DECIMAL(4,2), 
	Status CHAR(1) NOT NULL,
	CONSTRAINT pk_DVDID PRIMARY KEY (DVDID)
);

CREATE TABLE Members (
	MemberID INT(6) UNSIGNED,
	Forename VARCHAR(20) NOT NULL  ,
	Lastname VARCHAR(30) NOT NULL  ,
	Password VARCHAR (256) NOT NULL,
	Eircode VARCHAR(7) NOT NULL  ,
	Phone CHAR(10) NOT NULL  ,
	Email VARCHAR(100)   ,
	DOB Date NOT NULL  ,
	CardDetails VARCHAR(35),
	ExpireDate VARCHAR(5),
	CVV VARCHAR(3),
	CONSTRAINT PK_MemberID PRIMARY KEY (MemberID)
);



CREATE TABLE Rentals (
RentalID INT(10) UNSIGNED,
	MemberID INT(6) UNSIGNED,
DVDID INT(6) UNSIGNED,
RentalDate Date NOT NULL ,
RentalDueDate DATE NOT NULL,
	Status CHAR(1) NOT NULL,
	CONSTRAINT PK_RentalID PRIMARY KEY (RentalID),
	CONSTRAINT FK_MemberID FOREIGN KEY (MemberID) REFERENCES Members(MemberID),
	CONSTRAINT FK_DVDID FOREIGN KEY (DVDID) REFERENCES DVDs(DVDID)
 );

